import type { MotionVocabulary } from "../../brand/vocabulary";

/**
 * How Atomic speaks. Dense, mechanical, cursor-led. Hard cuts, composed
 * panels, product in windows with mono labels as interface feedback.
 */
export const atomicVocabulary: MotionVocabulary = {
  brandId: "atomic",
  entries: [
    {
      pattern: "headline-reveal",
      alias: "typeset statement",
      category: "typography",
      description: "Bold grotesk rising inside a mask on the deck grid, mono label above in cobalt.",
      roles: ["hook", "statement", "section-intro"],
      compatibleContent: ["short-headline", "brand-statement"],
      energy: "medium",
      duration: { min: 42, preferred: 60, max: 90 },
      constraints: { maxWords: 8, maxLines: 2 },
      goodFor: ["the one claim before the evidence", "a section title between builds"],
      avoidWhen: ["it would be the second type-only shot in a row"],
      brandOptions: { behaviour: "mask-rise", grid: true, align: "left", position: "center" },
    },
    {
      pattern: "knockout-statement",
      alias: "knockout plate",
      category: "typography",
      description: "Footage seen only through the letters, then the plate leaves or the letters fill solid.",
      roles: ["hook", "close"],
      compatibleContent: ["short-headline", "single-video"],
      energy: "high",
      duration: { min: 66, preferred: 90, max: 110 },
      constraints: { maxWords: 3, maxLines: 2 },
      goodFor: ["an intro that is judged on its first frame", "an end card that can be screenshotted"],
      avoidWhen: ["the clip contains readable client headlines"],
      brandOptions: { end: "plate-leaves", settle: 0.04 },
    },
    {
      pattern: "panel-mosaic",
      alias: "composed grid",
      category: "layout",
      description: "The reel's main register: 12×8 cell mosaic, panels butted, colour plates from the work's own palette.",
      roles: ["hook", "proof", "breathe"],
      compatibleContent: ["image-set", "single-video"],
      energy: "medium",
      duration: { min: 54, preferred: 66, max: 90 },
      constraints: { minItems: 2, maxItems: 5, maxWords: 3 },
      goodFor: ["opening mid-action on real work", "showing four projects in one frame"],
      avoidWhen: ["only one image exists"],
      brandOptions: { gap: false, plates: true },
    },
    {
      pattern: "browser-scroll",
      alias: "figma to live",
      category: "product",
      description: "Hairline browser window, chrome draws on, capture scrolls, window opens to full bleed.",
      roles: ["reveal", "proof"],
      compatibleContent: ["website"],
      energy: "medium",
      duration: { min: 60, preferred: 70, max: 100 },
      goodFor: ["the moment the design becomes the site"],
      avoidWhen: ["media is a static screenshot with no scroll"],
      brandOptions: { chrome: "hairline", open: true, width: 0.51 },
    },
    {
      pattern: "annotated-window",
      alias: "callouts",
      category: "product",
      description: "One build in a hairline window, mini-chrome callout boxes naming what was owned.",
      roles: ["detail", "proof"],
      compatibleContent: ["website"],
      energy: "medium",
      duration: { min: 66, preferred: 70, max: 100 },
      constraints: { maxLines: 4, maxWords: 40 },
      goodFor: ["making the partnership claim on real work"],
      avoidWhen: ["claims are not verifiable"],
      brandOptions: { calloutStyle: "window" },
    },
    {
      pattern: "floating-cards",
      alias: "cards on cobalt",
      category: "media",
      description: "UI crops floating on a full cobalt field, 18px radius, soft shadow.",
      roles: ["reveal", "detail"],
      compatibleContent: ["ui-fragments"],
      energy: "medium",
      duration: { min: 60, preferred: 70, max: 90 },
      goodFor: ["product UI without a demo"],
      avoidWhen: ["the shot before was already cobalt"],
      brandOptions: { field: "accent" },
    },
    {
      pattern: "structured-gallery",
      alias: "web gallery",
      category: "media",
      description: "Full-page designs fly in on arcs, rotate to settle, then the row drifts up.",
      roles: ["proof"],
      compatibleContent: ["image-set"],
      energy: "high",
      duration: { min: 66, preferred: 80, max: 100 },
      constraints: { minItems: 3, maxItems: 4 },
      goodFor: ["from one build to the whole body of work"],
      avoidWhen: ["the piece is under ten seconds"],
      brandOptions: { arrival: "fly", pan: true },
    },
    {
      pattern: "device-grid",
      alias: "phone wall",
      category: "product",
      description: "Six columns of real phone captures drifting against each other on black.",
      roles: ["proof"],
      compatibleContent: ["image-set"],
      energy: "medium",
      duration: { min: 60, preferred: 74, max: 90 },
      constraints: { minItems: 12, maxItems: 18 },
      goodFor: ["proving responsive without the word"],
      avoidWhen: ["fewer than twelve screens"],
      brandOptions: { columns: 6, drift: true },
    },
    {
      pattern: "logo-wall",
      alias: "client wall",
      category: "logo",
      description: "Rows of white-silhouette marks drifting one way, outlined mono capability tags the other.",
      roles: ["proof"],
      compatibleContent: ["logo-set"],
      energy: "low",
      duration: { min: 48, preferred: 56, max: 70 },
      goodFor: ["the roster, late in the piece"],
      avoidWhen: ["closing — Atomic closes on a title, not logos"],
      brandOptions: { behaviour: "drift", tags: true },
    },
    {
      pattern: "logo-outro",
      alias: "final title",
      category: "logo",
      description: "Name in bold grotesk, positioning line, mono line in cobalt, on the light ground with the rule grid.",
      roles: ["close"],
      compatibleContent: ["short-headline", "logo"],
      energy: "low",
      duration: { min: 48, preferred: 60, max: 90 },
      goodFor: ["the loop point of a hero reel"],
      avoidWhen: [],
      brandOptions: { grid: true, logoHeight: 120 },
    },
    {
      pattern: "split-reveal",
      alias: "editorial split",
      category: "layout",
      description: "Type block left, one tall capture right, hard mask.",
      roles: ["section-intro", "reveal"],
      compatibleContent: ["short-headline", "single-video"],
      energy: "medium",
      duration: { min: 60, preferred: 84, max: 100 },
      goodFor: ["an intro that has to read above the fold"],
      avoidWhen: [],
      brandOptions: { mediaSide: "right", ratio: "half", bleed: true },
    },
  ],
  preferences: {
    hook: ["panel-mosaic", "knockout-statement", "headline-reveal"],
    statement: ["headline-reveal"],
    "section-intro": ["headline-reveal", "split-reveal"],
    reveal: ["browser-scroll", "floating-cards", "split-reveal"],
    proof: ["annotated-window", "structured-gallery", "device-grid", "logo-wall", "panel-mosaic"],
    detail: ["annotated-window", "floating-cards"],
    breathe: ["panel-mosaic"],
    close: ["logo-outro", "knockout-statement"],
  },
};
