import type { MotionVocabulary } from "../../brand/vocabulary";

/**
 * How EdelGive speaks. Slow, centred, serif, photographic. Pages of a report
 * turning under a wave edge.
 */
export const edelgiveVocabulary: MotionVocabulary = {
  brandId: "edelgive",
  entries: [
    {
      pattern: "photo-statement",
      alias: "hero over landscape",
      category: "media",
      description: "Full-bleed landscape with a slow push and a scrim; centred serif headline rises line by line; body line and pill CTA land after.",
      roles: ["hook", "statement", "section-intro", "close"],
      compatibleContent: ["short-headline", "single-image", "single-video"],
      energy: "low",
      duration: { min: 70, preferred: 100, max: 150 },
      constraints: { maxWords: 12, maxLines: 3 },
      goodFor: ["opening on the mission", "a section title with a photograph behind it"],
      avoidWhen: ["no landscape or people photograph is available"],
      brandOptions: { scrim: 0.42, cta: true },
    },
    {
      pattern: "headline-reveal",
      alias: "report heading",
      category: "typography",
      description: "Centred serif heading on paper, last line in terracotta, one lead line under it.",
      roles: ["statement", "section-intro"],
      compatibleContent: ["short-headline", "brand-statement"],
      energy: "low",
      duration: { min: 54, preferred: 72, max: 110 },
      constraints: { maxWords: 12, maxLines: 3 },
      goodFor: ["a section title between photographic beats", "the thesis line"],
      avoidWhen: ["the previous beat was also type on paper"],
      brandOptions: { behaviour: "mask-rise", grid: false, align: "center", position: "center", emphasisLine: "last" },
    },
    {
      pattern: "stat-tiles",
      alias: "impact bento",
      category: "layout",
      description: "4×2 bento of blush plates with counting serif figures, alternating with rounded portrait photographs.",
      roles: ["proof"],
      compatibleContent: ["stat", "image-set"],
      energy: "medium",
      duration: { min: 80, preferred: 110, max: 160 },
      constraints: { minItems: 2, maxItems: 4 },
      goodFor: ["the numbers, all at once, with faces beside them"],
      avoidWhen: ["fewer than two figures", "no portrait photography"],
    },
    {
      pattern: "stat-reveal",
      alias: "one figure",
      category: "typography",
      description: "One serif figure counting up, terracotta label above, hairline, caption.",
      roles: ["proof", "detail"],
      compatibleContent: ["stat"],
      energy: "low",
      duration: { min: 60, preferred: 80, max: 110 },
      goodFor: ["one number that deserves its own page"],
      avoidWhen: ["stat-tiles was just shown"],
      brandOptions: { count: true, align: "center" },
    },
    {
      pattern: "pillar-index",
      alias: "three pillars",
      category: "layout",
      description: "Numbered vertical panels on a blush plate; the open panel carries a serif headline and body, the closed ones show rotated labels on the rail.",
      roles: ["section-intro", "detail", "reveal"],
      compatibleContent: ["short-headline", "body-copy"],
      energy: "low",
      duration: { min: 80, preferred: 110, max: 160 },
      constraints: { maxLines: 2, maxWords: 40 },
      goodFor: ["what we do, as a structure", "three offerings without three shots"],
      avoidWhen: ["fewer than two items to index"],
    },
    {
      pattern: "split-reveal",
      alias: "spread",
      category: "layout",
      description: "Terracotta label, serif headline and body on the left; one rounded photograph on the right, fading in.",
      roles: ["reveal", "section-intro", "detail"],
      compatibleContent: ["short-headline", "single-image"],
      energy: "low",
      duration: { min: 70, preferred: 96, max: 140 },
      goodFor: ["a claim beside its evidence"],
      avoidWhen: [],
      brandOptions: { mediaSide: "right", ratio: "half", bleed: false },
    },
    {
      pattern: "structured-gallery",
      alias: "report covers",
      category: "media",
      description: "Three rounded cards clip open from their bottom edge in sequence, no rotation, no drift.",
      roles: ["proof", "breathe"],
      compatibleContent: ["image-set"],
      energy: "low",
      duration: { min: 70, preferred: 90, max: 130 },
      constraints: { minItems: 3, maxItems: 3 },
      goodFor: ["reports, covers, three stories"],
      avoidWhen: ["images are UI"],
      brandOptions: { arrival: "rail", pan: false },
    },
    {
      pattern: "logo-wall",
      alias: "partners",
      category: "logo",
      description: "Partner marks in their own colours on white tiles, appearing in reading order.",
      roles: ["proof", "close"],
      compatibleContent: ["logo-set"],
      energy: "low",
      duration: { min: 60, preferred: 80, max: 110 },
      goodFor: ["the partners, late"],
      avoidWhen: ["opening"],
      brandOptions: { behaviour: "grid", tags: false, silhouette: false, tiles: true },
    },
    {
      pattern: "browser-scroll",
      alias: "the site",
      category: "product",
      description: "Website capture in a plain rounded frame, no chrome, centred on paper.",
      roles: ["reveal", "detail"],
      compatibleContent: ["website"],
      energy: "low",
      duration: { min: 70, preferred: 90, max: 130 },
      goodFor: ["showing the website itself, once"],
      avoidWhen: ["it would be the hook"],
      brandOptions: { chrome: "plain", open: false, width: 0.6 },
    },
    {
      pattern: "logo-outro",
      alias: "closing card",
      category: "logo",
      description: "Mark centred on paper, one serif line, navy pill CTA and the URL.",
      roles: ["close"],
      compatibleContent: ["logo", "short-headline"],
      energy: "low",
      duration: { min: 60, preferred: 84, max: 120 },
      goodFor: ["the last frame"],
      avoidWhen: [],
      brandOptions: { grid: false, logoHeight: 110 },
    },
    {
      pattern: "panel-mosaic",
      alias: "photo bento",
      category: "layout",
      description: "Gapped, rounded photo panels with blush plates. Used sparingly.",
      roles: ["breathe", "proof"],
      compatibleContent: ["image-set"],
      energy: "low",
      duration: { min: 70, preferred: 90, max: 120 },
      constraints: { minItems: 2, maxItems: 4 },
      goodFor: ["a breath of photography between text beats"],
      avoidWhen: ["stat-tiles is in the same piece"],
      brandOptions: { gap: true, plates: true },
    },
  ],
  preferences: {
    hook: ["photo-statement", "headline-reveal"],
    statement: ["headline-reveal", "photo-statement"],
    "section-intro": ["headline-reveal", "photo-statement", "pillar-index"],
    reveal: ["split-reveal", "pillar-index", "browser-scroll"],
    proof: ["stat-tiles", "split-reveal", "structured-gallery", "logo-wall", "stat-reveal"],
    detail: ["pillar-index", "split-reveal", "stat-reveal"],
    breathe: ["panel-mosaic", "structured-gallery"],
    close: ["logo-outro", "photo-statement"],
  },
};
